#!/usr/bin/perl
#Name: Antonio Salgado Lemus
#CS 410W
#Description: the program will create 4 child processes. Each process should generate
#200 random numbers bewteen 100 through 1000.

use IO::Handle;
pipe(I1,O1);
pipe(I2,O2);
O1->autoflush(1);
O2->autoflush(1);

die("Usage: argv.pl length width") if (@ARGV != 3);
 
$begin = $ARGV[0];
$end  = $ARGV[1]; 
$count =$ARGV[2];

foreach $i (0..3)
{
  $ids[$i]=fork();
  if ($ids[$i]==0)
    {
      # This is the child process
      &child;      
    }
}

# This is the parent process

foreach $i (0..3)
{ 
  $x = waitpid $ids[$i], $FLAGS;
  	$ids[$i] = <I1>;
	$a++;
	if($a==4){
		$sum=$ids[$i]+$sum;
		$globals=$sum/($count*4);
		$global = sprintf("%.1f", $globals);
		print "Range of numbers: $ARGV[0] through $ARGV[1]\n";
        	print "Numbers generated by each process: $ARGV[2]\n";
        	printf "Global Mean (rounded to nearest tenth): $global\n\n";
		print "Analysis compared to the global mean: \n\n";
		print"Process\t\tPID\tMean\tBelow\tAbove\n";
	}else{
		$sum=$ids[$i]+$sum;
	}
	
	print O2 "$global\n";

	#print STDOUT "Parent: $d1\n";
}	
sub child
{
  for( $a = 0; $a < $count; $a = $a + 1 ) {
 
    	$random = int( rand($end-$begin+1)) + $begin;
    	$arr[$i]+=$random; 
		
   }
	$sum=$arr[$i];
	$total=$sum/$count;
	$totals = sprintf("%.1f", $total);

	   print O1 "$sum\n";
  	sleep (5+rand(25));

	print "$i\t\t $$ \t $totals \t ? \t ? \n";
  exit;
	
}
